## Q1 : Arrays

In [2]:
import numpy

def arrays(arr):
    return(numpy.array(arr[::-1], float))

arr = input().strip().split(' ')

result = arrays(arr)

print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Q2 : Shape and Reshape

In [3]:
import numpy as np

arr =np.array(list(map(int,input().split())))

arr.shape=(3,3)

print(arr)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q3 : Transpose and Flatten

In [4]:
import numpy as np

a, b = map(int, input().split())

arr = np.array([input().strip().split() for i in range(a)], int)

print (arr.transpose())

print (arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Q4: Concatenate

In [5]:
import numpy as np

a, b, c = map(int,input().split())

arr1 = np.array([input().split() for i in range(a)],int)
arr2 = np.array([input().split() for i in range(b)],int)

print(np.concatenate((arr1, arr2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Q5 : Zeros and Ones

In [6]:
import numpy as np

arr = list(map(int,input().split()))

print(np.zeros(arr,int))

print(np.ones(arr,int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Q6: Eye and Identity

In [7]:
import numpy as np
np.set_printoptions(sign = ' ')

a, b = map(int,input().split())

print(np.eye(a, b, k = 0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Q7: Array Mathematics

In [9]:
import numpy as np

a, b = map(int,input().split())

A= np.array([list(map(int,input().split())) for i in range(a)])
B= np.array([list(map(int,input().split())) for i in range(a)])

print(A + B)                    
print(A - B)                     
print(A * B)                   
print(A // B)                  
print(A % B)                    
print(A**B)                    

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Q8 : Floor, Ceil and Rint

In [10]:
import numpy as np
np.set_printoptions(sign=' ')

arr = np.array(input().split(),float)

print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Q9 : Sum and Prod

In [11]:
import numpy as np

a, b = map(int, input().split())

arr = np.array([input().split() for i in range(a)],int)

print(np.prod(np.sum(arr, axis=0), axis=0))

2 2
1 2
3 4
24


## Q10 : Min and Max

In [12]:
import numpy as np 

a, b = map(int, input().split())

arr = np.array([input().split() for i in range(a)],int)

print(np.max(np.min(arr,axis=1)))

4 2
2 5
3 7
1 3
4 0
3


## Q11 : Min, Var and Std

In [13]:
import numpy as np

a, b = map(int,input().split())

arr = np.array([input().split() for i in range(a)],int)

print(np.mean(arr,axis = 1))
print(np.var(arr,axis = 0))
print(round(np.std(arr,axis=None),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## Q12 : Dot and Cross

In [16]:
import numpy as np

n = int(input())

a = np.array([input().split() for i in range(n)],int)
b = np.array([input().split() for i in range(n)],int)

print(np.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## Q13 : Inner and Outer

In [17]:
import numpy as np

a = np.array(input().split(), int)
b = np.array(input().split(), int)

print(np.inner(a, b))
print(np.outer(a, b))

0 1
2 3
3
[[0 0]
 [2 3]]


## Q14 : Polynomials

In [18]:
import numpy as np

poly = np.array(input().split(),float)

n = int(input())

print(np.polyval(poly,n))

1.1 2 3
0
3.0


## Q15 : Linear Algebra

In [19]:
import numpy as np

n = int(input())

a = np.array([input().split() for i in range(n)],float)

print(round(np.linalg.det(a),2))

2
1.1 1.1
1.1 1.1
0.0
